channel_sources:
  - valmar,conda-forge,defaults
channel_targets:
  - valmar main

python:
  # part of a zip_keys: python, python_impl, numpy
  - 2.7.15 *_cpython  # [not (aarch64 or ppc64le or win)]]
python_impl:
  # part of a zip_keys: python, python_impl, numpy
  - cpython   # [not (aarch64 or ppc64le or win)]]
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.16  # [not (aarch64 or ppc64le or win)]]
